apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: wordpress-namespace
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/wordpress
